# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Test, Lint

on:
  push:
    branches: [ main, exercise5 ]
  pull_request:
    branches: [ main, exercise5 ]

jobs:
  build-test-lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    env:
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: test

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: KarakoA/setup-neo4j@v1.1.1
        with:
          password: test
          # user hardcoded to neo4j by action
      - run: |
              npm ci
              npm run lint
              npm run test
        working-directory: ./backend/
