# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Test, Lint

on:
  push:
    branches: [ main, exercise3 ]
  pull_request:
    branches: [ main, exercise3 ]

jobs:
  build-test-lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
        working-directory: ./webapp
      - run: npm run lint
        working-directory: ./webapp
      - run: npm run test:unit
        working-directory: ./webapp

      - run: npm ci
        working-directory: ./backend
      - run: npm run lint
        working-directory: ./backend
